require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('config.completion')
require('config.lazy')
require('config.colorscheme')
